version: '3'

services:
  web:
    build: .
    restart: on-failure:10
    container_name: bookstore_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    container_name: bookstore_psql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "bookstore"
      POSTGRES_USER: "bookstore"
      POSTGRES_PASSWORD: "bookstore"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
