# Generated by Django 3.0.1 on 2020-01-02 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('description', models.CharField(max_length=160, verbose_name='Description')),
                ('editable', models.BooleanField(default=True, editable=False, verbose_name='Is Editable')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.District', verbose_name='District')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_user.address_set+', to='contenttypes.ContentType')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.Province', verbose_name='Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CorporateAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Address')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('tax_room', models.CharField(max_length=100, verbose_name='Tax Room')),
                ('tax_number', models.CharField(max_length=11, verbose_name='Tax Number')),
            ],
            options={
                'verbose_name': 'Corporate Address',
                'verbose_name_plural': 'Corporate Addresses',
                'db_table': 'corporate_addresses',
            },
            bases=('user.address',),
        ),
        migrations.CreateModel(
            name='IndividualAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'Individual Address',
                'verbose_name_plural': 'Individual Addresses',
                'db_table': 'individual_addresses',
            },
            bases=('user.address',),
        ),
    ]
